version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ai_model:/app/ai_model
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents conflicts with host's node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1/
    command: npm start  # 🚀 Add this to start the app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
