version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ai_model:/app/ai_model
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend  # Explicitly define context
      dockerfile: Dockerfile  # Define the Dockerfile path if needed
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
